import { Inter } from "next/font/google";
import "./globals.css";
import "./app.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";
import { BlogProvider } from "@/context/blogProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <BlogProvider>{children}</BlogProvider>
        <Footer />
      </body>
    </html>
  );
}
